# Generated by Django 4.0.6 on 2022-07-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=30)),
                ('name_2', models.CharField(max_length=40)),
                ('name_3', models.CharField(max_length=40)),
                ('file1', models.FileField(upload_to='documents/word/')),
                ('file2', models.FileField(upload_to='documents/word/')),
                ('file3', models.FileField(upload_to='documents/word/')),
                ('file_processed', models.FileField(upload_to='documents/word/')),
            ],
        ),
    ]
