# Generated by Django 4.0.6 on 2022-07-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_document_file_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name_3',
        ),
    ]
