# Generated by Django 4.0.6 on 2022-07-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_document_name_1_remove_document_name_2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Mydocument',
        ),
    ]
