# Generated by Django 4.0.6 on 2022-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mydocument_file_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydocument',
            name='file_processed',
            field=models.FileField(default='documents/word/ssm.docx', null=True, upload_to=''),
        ),
    ]
