# Generated by Django 4.0.6 on 2022-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_mydocument_file_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
