# Generated by Django 4.0.6 on 2022-07-13 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_bugreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreports',
            name='report',
            field=models.TextField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
    ]
